Internal Server Error: /api/users/register/
Traceback (most recent call last):
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\users\views.py", line 125, in post
    if serializer.is_valid():
       ~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\serializers.py", line 223, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\serializers.py", line 442, in run_validation
    value = self.to_internal_value(data)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\serializers.py", line 495, in to_internal_value
    for field in fields:
                 ^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\serializers.py", line 378, in _writable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\serializers.py", line 1103, in get_fields
    field_class, field_kwargs = self.build_field(
                                ~~~~~~~~~~~~~~~~^
        source, info, model, depth
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\serializers.py", line 1249, in build_field
    return self.build_unknown_field(field_name, model_class)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\serializers.py", line 1367, in build_unknown_field
    raise ImproperlyConfigured(
    ...<2 lines>...
    )
django.core.exceptions.ImproperlyConfigured: Field name `phone_number` is not valid for model `User` in `users.serializers.UserSerializer`.
"POST /api/users/register/ HTTP/1.1" 500 149783
Internal Server Error: /swagger/
Traceback (most recent call last):
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\views.py", line 112, in get
    schema = generator.get_schema(request, self.public)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 276, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
                    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 482, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 524, in get_operation
    operation = view_inspector.get_operation(operation_keys)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 32, in get_operation
    body = self.get_request_body_parameters(consumes)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 71, in get_request_body_parameters
    serializer = self.get_request_serializer()
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 118, in get_request_serializer
    body_override = self._get_request_body_override()
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 104, in _get_request_body_override
    raise SwaggerGenerationError("request_body can only be applied to (" + ','.join(self.body_methods) +
                                 "); are you looking for query_serializer or manual_parameters?")
drf_yasg.errors.SwaggerGenerationError: request_body can only be applied to (PUT,PATCH,POST,DELETE); are you looking for query_serializer or manual_parameters?
"GET /swagger/?format=openapi HTTP/1.1" 500 157200
Internal Server Error: /swagger/
Traceback (most recent call last):
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\views.py", line 112, in get
    schema = generator.get_schema(request, self.public)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 276, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
                    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 482, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 524, in get_operation
    operation = view_inspector.get_operation(operation_keys)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 32, in get_operation
    body = self.get_request_body_parameters(consumes)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 71, in get_request_body_parameters
    serializer = self.get_request_serializer()
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 118, in get_request_serializer
    body_override = self._get_request_body_override()
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 104, in _get_request_body_override
    raise SwaggerGenerationError("request_body can only be applied to (" + ','.join(self.body_methods) +
                                 "); are you looking for query_serializer or manual_parameters?")
drf_yasg.errors.SwaggerGenerationError: request_body can only be applied to (PUT,PATCH,POST,DELETE); are you looking for query_serializer or manual_parameters?
"GET /swagger/?name=schema-swagger-ui HTTP/1.1" 500 157325
Internal Server Error: /swagger/
Traceback (most recent call last):
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\views.py", line 112, in get
    schema = generator.get_schema(request, self.public)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 276, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
                    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 482, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 524, in get_operation
    operation = view_inspector.get_operation(operation_keys)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 32, in get_operation
    body = self.get_request_body_parameters(consumes)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 71, in get_request_body_parameters
    serializer = self.get_request_serializer()
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 118, in get_request_serializer
    body_override = self._get_request_body_override()
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 104, in _get_request_body_override
    raise SwaggerGenerationError("request_body can only be applied to (" + ','.join(self.body_methods) +
                                 "); are you looking for query_serializer or manual_parameters?")
drf_yasg.errors.SwaggerGenerationError: request_body can only be applied to (PUT,PATCH,POST,DELETE); are you looking for query_serializer or manual_parameters?
"GET /swagger/?format=openapi HTTP/1.1" 500 157200
Internal Server Error: /swagger/
Traceback (most recent call last):
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\views.py", line 112, in get
    schema = generator.get_schema(request, self.public)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 276, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
                    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 482, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 524, in get_operation
    operation = view_inspector.get_operation(operation_keys)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 32, in get_operation
    body = self.get_request_body_parameters(consumes)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 71, in get_request_body_parameters
    serializer = self.get_request_serializer()
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 118, in get_request_serializer
    body_override = self._get_request_body_override()
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 104, in _get_request_body_override
    raise SwaggerGenerationError("request_body can only be applied to (" + ','.join(self.body_methods) +
                                 "); are you looking for query_serializer or manual_parameters?")
drf_yasg.errors.SwaggerGenerationError: request_body can only be applied to (PUT,PATCH,POST,DELETE); are you looking for query_serializer or manual_parameters?
"GET /swagger/?format=openapi HTTP/1.1" 500 157200
Internal Server Error: /api/token/
Traceback (most recent call last):
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework_simplejwt\views.py", line 41, in post
    serializer = self.get_serializer(data=request.data)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\generics.py", line 114, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\users\views.py", line 511, in __init__
    self.fields.pop('username')
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "<frozen _collections_abc>", line 950, in pop
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\utils\serializer_helpers.py", line 170, in __getitem__
    return self.fields[key]
           ~~~~~~~~~~~^^^^^
KeyError: 'username'
"POST /api/token/ HTTP/1.1" 500 114593
Internal Server Error: /swagger/
Traceback (most recent call last):
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\views.py", line 112, in get
    schema = generator.get_schema(request, self.public)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 276, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
                    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 482, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 524, in get_operation
    operation = view_inspector.get_operation(operation_keys)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 32, in get_operation
    body = self.get_request_body_parameters(consumes)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 71, in get_request_body_parameters
    serializer = self.get_request_serializer()
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 118, in get_request_serializer
    body_override = self._get_request_body_override()
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 104, in _get_request_body_override
    raise SwaggerGenerationError("request_body can only be applied to (" + ','.join(self.body_methods) +
                                 "); are you looking for query_serializer or manual_parameters?")
drf_yasg.errors.SwaggerGenerationError: request_body can only be applied to (PUT,PATCH,POST,DELETE); are you looking for query_serializer or manual_parameters?
"GET /swagger/?format=openapi HTTP/1.1" 500 157710
Internal Server Error: /api/token/
Traceback (most recent call last):
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework_simplejwt\views.py", line 41, in post
    serializer = self.get_serializer(data=request.data)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\generics.py", line 114, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\users\views.py", line 511, in __init__
    self.fields.pop('username')
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "<frozen _collections_abc>", line 950, in pop
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\utils\serializer_helpers.py", line 170, in __getitem__
    return self.fields[key]
           ~~~~~~~~~~~^^^^^
KeyError: 'username'
"POST /api/token/ HTTP/1.1" 500 114602
Internal Server Error: /api/token/
Traceback (most recent call last):
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework_simplejwt\views.py", line 41, in post
    serializer = self.get_serializer(data=request.data)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\generics.py", line 114, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\users\views.py", line 533, in __init__
    self.fields.pop('username')
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "<frozen _collections_abc>", line 950, in pop
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\utils\serializer_helpers.py", line 170, in __getitem__
    return self.fields[key]
           ~~~~~~~~~~~^^^^^
KeyError: 'username'
"POST /api/token/ HTTP/1.1" 500 114566
Internal Server Error: /swagger/
Traceback (most recent call last):
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\views.py", line 112, in get
    schema = generator.get_schema(request, self.public)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 276, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
                    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 482, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 524, in get_operation
    operation = view_inspector.get_operation(operation_keys)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 32, in get_operation
    body = self.get_request_body_parameters(consumes)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 71, in get_request_body_parameters
    serializer = self.get_request_serializer()
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 118, in get_request_serializer
    body_override = self._get_request_body_override()
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 104, in _get_request_body_override
    raise SwaggerGenerationError("request_body can only be applied to (" + ','.join(self.body_methods) +
                                 "); are you looking for query_serializer or manual_parameters?")
drf_yasg.errors.SwaggerGenerationError: request_body can only be applied to (PUT,PATCH,POST,DELETE); are you looking for query_serializer or manual_parameters?
"GET /swagger/?format=openapi HTTP/1.1" 500 157710
Internal Server Error: /swagger/
Traceback (most recent call last):
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\views.py", line 112, in get
    schema = generator.get_schema(request, self.public)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 276, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
                    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 482, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 524, in get_operation
    operation = view_inspector.get_operation(operation_keys)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 32, in get_operation
    body = self.get_request_body_parameters(consumes)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 71, in get_request_body_parameters
    serializer = self.get_request_serializer()
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 118, in get_request_serializer
    body_override = self._get_request_body_override()
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 104, in _get_request_body_override
    raise SwaggerGenerationError("request_body can only be applied to (" + ','.join(self.body_methods) +
                                 "); are you looking for query_serializer or manual_parameters?")
drf_yasg.errors.SwaggerGenerationError: request_body can only be applied to (PUT,PATCH,POST,DELETE); are you looking for query_serializer or manual_parameters?
"GET /swagger/?format=openapi HTTP/1.1" 500 157905
Internal Server Error: /redoc/
Traceback (most recent call last):
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\views.py", line 112, in get
    schema = generator.get_schema(request, self.public)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 276, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
                    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 482, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 524, in get_operation
    operation = view_inspector.get_operation(operation_keys)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 32, in get_operation
    body = self.get_request_body_parameters(consumes)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 71, in get_request_body_parameters
    serializer = self.get_request_serializer()
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 118, in get_request_serializer
    body_override = self._get_request_body_override()
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 104, in _get_request_body_override
    raise SwaggerGenerationError("request_body can only be applied to (" + ','.join(self.body_methods) +
                                 "); are you looking for query_serializer or manual_parameters?")
drf_yasg.errors.SwaggerGenerationError: request_body can only be applied to (PUT,PATCH,POST,DELETE); are you looking for query_serializer or manual_parameters?
"GET /redoc/?format=openapi HTTP/1.1" 500 157702
Internal Server Error: /swagger/
Traceback (most recent call last):
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\views.py", line 112, in get
    schema = generator.get_schema(request, self.public)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 276, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
                    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 482, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 524, in get_operation
    operation = view_inspector.get_operation(operation_keys)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 32, in get_operation
    body = self.get_request_body_parameters(consumes)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 71, in get_request_body_parameters
    serializer = self.get_request_serializer()
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 118, in get_request_serializer
    body_override = self._get_request_body_override()
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 104, in _get_request_body_override
    raise SwaggerGenerationError("request_body can only be applied to (" + ','.join(self.body_methods) +
                                 "); are you looking for query_serializer or manual_parameters?")
drf_yasg.errors.SwaggerGenerationError: request_body can only be applied to (PUT,PATCH,POST,DELETE); are you looking for query_serializer or manual_parameters?
"GET /swagger/?format=openapi HTTP/1.1" 500 157983
Internal Server Error: /swagger/
Traceback (most recent call last):
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\views.py", line 112, in get
    schema = generator.get_schema(request, self.public)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 276, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
                    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 482, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 524, in get_operation
    operation = view_inspector.get_operation(operation_keys)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 32, in get_operation
    body = self.get_request_body_parameters(consumes)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 71, in get_request_body_parameters
    serializer = self.get_request_serializer()
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 118, in get_request_serializer
    body_override = self._get_request_body_override()
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 104, in _get_request_body_override
    raise SwaggerGenerationError("request_body can only be applied to (" + ','.join(self.body_methods) +
                                 "); are you looking for query_serializer or manual_parameters?")
drf_yasg.errors.SwaggerGenerationError: request_body can only be applied to (PUT,PATCH,POST,DELETE); are you looking for query_serializer or manual_parameters?
"GET /swagger/?format=openapi HTTP/1.1" 500 157744
Internal Server Error: /swagger/
Traceback (most recent call last):
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\views.py", line 112, in get
    schema = generator.get_schema(request, self.public)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 276, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
                    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 482, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 524, in get_operation
    operation = view_inspector.get_operation(operation_keys)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 32, in get_operation
    body = self.get_request_body_parameters(consumes)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 71, in get_request_body_parameters
    serializer = self.get_request_serializer()
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 118, in get_request_serializer
    body_override = self._get_request_body_override()
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 104, in _get_request_body_override
    raise SwaggerGenerationError("request_body can only be applied to (" + ','.join(self.body_methods) +
                                 "); are you looking for query_serializer or manual_parameters?")
drf_yasg.errors.SwaggerGenerationError: request_body can only be applied to (PUT,PATCH,POST,DELETE); are you looking for query_serializer or manual_parameters?
"GET /swagger/?format=openapi HTTP/1.1" 500 157744
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
